algoritmo "semnome"
// Função :
// Autor :
// Data : 6/26/2021
// Seção de Declarações 
var
x, y: inteiro
Procedimento Soma(a,b: inteiro)
Inicio
   a <- a + 1
   b <- b + 2
   EscrevaL("Valor de a = ", a)
   EscrevaL("Valor de b = ", b)
   EscrevaL("Valor de a + b = ", a + b)
FimProcedimento
inicio
   x <- 4
   y <- 8
   Soma(x,y)
   EscrevaL("Valor de x = ", x)
   EscrevaL("Valor de y = ", y)
fimalgoritmo
